### PR TITLE
When download the llvm toolkits with 'wget', there will be an extra slash('/') in the URL path.

### PR DESCRIPTION
**Pull request by rootkiter**
[BUG state] $ wget [...skip...]/llvmorg-10.0.0//clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz.

So I wrote this patch.

### CODE REVIEW

**Comment by vitalych** [comment]
Thanks! Did you experience any build failure because of this?

A better commit message would look like this:
```
makefile: remove extra slash in LLVM URL

When downloading the llvm-toolkits, there is an extra slash('/') in M…
…akefile.

$ wget /.../llvmorg-10.0.0//clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz.
```

**Comment by rootkiter** [comment]
Yes, the source code package of llvm cannot be downloaded correctly.

**Comment by rootkiter** [comment]
wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0//clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz

**Comment by vitalych** [comment]
Seems to work for me. What system are you using?

**Comment by rootkiter** [comment]
Ubuntu18.04

--------------原始邮件--------------
发件人："Vitaly Chipounov ***@***.***&gt;;
发送时间：2021年5月21日(星期五) 晚上8:00
收件人："S2E/s2e" ***@***.***&gt;;
抄送："rootkiter ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [S2E/s2e] When download the llvm toolkits with 'wget', there will be an extra slash('/') in the URL path. (#27)
-----------------------------------

 

 
Seems to work for me. What system are you using?

**Comment by rootkiter** [comment]
when you run 'docker build -t mys2e:v0 .':

image

**Comment by vitalych** [comment]
I also get 302 Found, it's not an error code. Does it fail to download?
Anyway, the patch looks fine, I will apply it after you fix the commit message.

**Comment by rootkiter** [comment]
So. No data first and then 302 is right?

**Comment by vitalych** [comment]
Why did you close it? It wasn't merged.

**Pull request closed without merging**
