### PR TITLE
libcpu: fix wrong reported memory access width 

### PR DESCRIPTION
**Pull request by mkyybx**

### CODE REVIEW

**Comment by vitalych** [comment]
Please do `git pull --rebase origin master` in order to not have merge in the PR.

**Comment by vitalych** [comment]
Do not close it, but force-push once you fixed.

**Comment by mkyybx** [comment]
Sorry but I'm not familiar with git operations. I don't know I closed it. Now I reopened it after I removed the merging commits. Thanks.

**Comment by vitalych** [comment]
> Sorry but I'm not familiar with git operations. I don't know I closed it. Now I reopened it after I removed the merging commits. Thanks.

No worries, it looks good now.

**Comment by vitalych** [comment]
How did you find this bug? Any chance you could add a test case? I suppose it would be similar to this one: https://github.com/S2E/s2e/tree/master/testsuite/basic8-tracers

**Comment by mkyybx** [comment]
I just happen to find S2E marked a memory read as a 4-byte-read (through the `getWidth()` function of the `value` argument of `onBeforeSymbolicDataMemoryAccess` signal) where the original assembly code is
`0xffffffff81638455 <tcp_v4_rcv+197>: mov    r15,QWORD PTR [rbx+0x18]`
and I thought this is definitely wrong at least in my defination. The correct answer should be 64 bits or 8 bytes. 

Here is the simple code that I believe could demonstrate the bug:

#include <stdio.h>
#include <stdlib.h>
int main() {
    unsigned long int* ptr = (unsigned long int*)malloc(sizeof(unsigned long int));
    unsigned long int val = *ptr;
    printf("%ld\n", val);
}

The disassembly is:

Dump of assembler code for function main:
   0x0000000000001169 <+0>:     endbr64
   0x000000000000116d <+4>:     push   rbp
   0x000000000000116e <+5>:     mov    rbp,rsp
   0x0000000000001171 <+8>:     sub    rsp,0x10
   0x0000000000001175 <+12>:    mov    edi,0x8
   0x000000000000117a <+17>:    call   0x1070 <malloc@plt>
   0x000000000000117f <+22>:    mov    QWORD PTR [rbp-0x10],rax
   0x0000000000001183 <+26>:    mov    rax,QWORD PTR [rbp-0x10]
   0x0000000000001187 <+30>:    mov    rax,QWORD PTR [rax]
   0x000000000000118a <+33>:    mov    QWORD PTR [rbp-0x8],rax
   0x000000000000118e <+37>:    mov    rax,QWORD PTR [rbp-0x8]
   0x0000000000001192 <+41>:    mov    rsi,rax
   0x0000000000001195 <+44>:    lea    rdi,[rip+0xe68]        # 0x2004
   0x000000000000119c <+51>:    mov    eax,0x0
   0x00000000000011a1 <+56>:    call   0x1060 <printf@plt>
   0x00000000000011a6 <+61>:    mov    eax,0x0
   0x00000000000011ab <+66>:    leave
   0x00000000000011ac <+67>:    ret

I guess every `mov` instrcution operating on `QWORD PTR` would be reported as a 4-byte-read if the bug is not fixed.

**Comment by vitalych** [comment]
Was it only for INSTR_BEFORE_MEMORY_ACCESS that you saw the problem? After looking at the code, there are calls like this :`INSTR_BEFORE_MEMORY_ACCESS(ptr, 0, 0);` which would explain the size (hard-coded 0 is 4-bytes). Other invocations use variables with proper size. I think it would make more sense to cast at the call site if that's the case.

**Comment by mkyybx** [comment]
Yes I agree that it would make sense, but can we know the value "before the memory access"? Besides, I feel my fix may also make sense. If I understand correctly, the width of the memory access is determined in the TCG code. The TCG-LLVM translator (`TCGLLVMTranslator::generateQemuMemOp()`) will compile different helper functions (e.g., `helper_ldl_mmu`, `helper_ldq_mmu`) into LLVM code according to the `helper_size`. Since the helper functions are generated from the template with the difference on DATA_SIZE macro, and therefore using DATA_SIZE macro in the INSTR_BEFORE_MEMORY_ACCESS should also work.

**Comment by vitalych** [comment]
Yes, your fix also works. It was more of a style remark, to avoid having the macro depend on another macro.

**Comment by mkyybx** [comment]
Then how about changing `#define INSTR_BEFORE_MEMORY_ACCESS(vaddr, value, flags)` to `#define INSTR_BEFORE_MEMORY_ACCESS(vaddr, value, size, flags)`? This way the DATA_SIZE can be passed at the caller's site without knowing the `value`.

**Comment by vitalych** [comment]
Sounds goods

**Comment by mkyybx** [comment]
I made changes to move the size parameter to the caller site to avoid the recursive macro calling.

**Comment by mkyybx** [comment]
Just happen to have another personal question: Is it possible to make S2E directly run on LLVM IR code compiled from the source instead of the one lifted from the binary? I'm thinking this will retain some source code info like type info. Thanks.

**Comment by vitalych** [comment]
No directly. S2E can only interpret low-level machine instructions. What you could do instead is run KLEE inside S2E, this way you will have the advantages of both (source code for KLEE + whole system symbolic execution without limitations of KLEE's function models).

**Comment by mkyybx** [comment]
Thank you.

**Review by vitalych — APPROVED** [review]

**Comment by vitalych** [comment]
Please run clang-format and it should be good to go.

**Comment by mkyybx** [comment]
I just applied clang-format. But I didn't notice difference from my original commits. Hope it will pass the check.

**Pull request merged**
