### PR TITLE
Fix the errno missing dependency

### PR DESCRIPTION
**Pull request by MingxuanYao0528**

### CODE REVIEW

**Comment by vitalych** [comment]
Looks good. Please run clang format and add `libq: ` prefix to the commit message.

**Comment by MingxuanYao0528** [comment]
I fixed the format of `error.c` using clang-format.

**Comment by vitalych** [comment]
Please squash your commits and force push.

**Comment by MingxuanYao0528** [comment]
squashed and pushed ;)

**Pull request merged**
